name: VotingSample
ingress:
  - name: ingress
    bindings:
      - port: 8080
    rules:
      - path: /vote
        service: vote
      - path: /results
        service: results      
services:
- name: vote
  project: vote/vote.csproj
- name: redis
  image: redis
  bindings:
    - port: 6379
      connectionString: ${host}:${port}
- name: redis-cli
  image: redis
  args: "redis-cli -h redis MONITOR"
- name: worker
  project: worker/worker.csproj
- name: postgres
  image:  postgres
  env:
  - name: POSTGRES_PASSWORD
    value: "pass@word1"
  - name: LISTEN_ADDRESSES
    value: "*"
  bindings:
  - port: 5432
    connectionString: Server=${host};Port=${port};User Id=postgres;Password=${env:POSTGRES_PASSWORD};
- name: postgres-browser
  image: dpage/pgadmin4
  env:
  - name: PGADMIN_DEFAULT_EMAIL
    value: "test@example.com"
  - name: PGADMIN_DEFAULT_PASSWORD
    value: "pass@word1"
  args: "--add-host=docker:127.0.0.1 --add-host=docker2:192.168.1.14"
  bindings:
  - protocol: http
    containerPort: 80
- name: results
  project: results/results.csproj
